version: '3.8'
services:
  flask-app:
    build: .
    networks:
      - stf_network
    volumes:
      - app_data:/app/data

  nginx-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - stf_network
    depends_on:
      - flask-app

networks:
  stf_network:
    driver: bridge

volumes:
  app_data:
