name: CI-CD Pipeline

on:
  push:
    branches: [ develop, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar a EC2 y Desplegar
        uses: appleboy/ssh-action@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GH_TOKEN
          script: |
            # 1. Forzar la descarga exacta desde GitHub (ignora diferencias locales)
            cd /home/ubuntu/Proyecto-devops
            git fetch https://${GH_TOKEN}@github.com/CbassT1/Proyecto-devops.git develop
            git reset --hard FETCH_HEAD
            
            # 2. Levantar la aplicacion con Docker
            cd app-docker
            sudo DOCKER_BUILDKIT=0 docker-compose down
            sudo DOCKER_BUILDKIT=0 docker-compose up -d --build
            
            # 3. Pruebas automatizadas
            echo "Esperando 10 segundos para que inicie la app..."
            sleep 10
            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080)
            
            if [ "$HTTP_STATUS" == "200" ]; then
              echo "Prueba exitosa. Codigo 200 OK. Despliegue completado."
            else
              echo "Fallo en la prueba. La app no responde."
              chmod +x ../rollback.sh
              ../rollback.sh
              exit 1
            fi